/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform --format png 
Files: scene.gltf [4.2KB] > /Users/ib-scott/Documents/dev/popopshuv/thumos-hydrogen/public/3d/pouch2/scene-transformed.glb [254.29KB] (-5955%)
Author: Polygon Alley (https://sketchfab.com/jmayala)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/protein-sachet-884d67946a954f43b03727a73121c5bd
Title: Protein Sachet
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box001__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
